# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('Mname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_type', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_type', models.CharField(max_length=30)),
                ('Area_code', models.CharField(max_length=3)),
                ('Number', models.CharField(max_length=8)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
            ],
        ),
    ]
