# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181007_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_type', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.IntegerField(max_length=5)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='Area_code',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Number',
            field=models.IntegerField(max_length=8),
        ),
    ]
