# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181007_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Address_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='State',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Zip',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Fname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Lname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Mname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='Date_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Area_code',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Number',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Phone_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
