# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0006_auto_20181007_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_type', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=20, null=True)),
                ('State', models.CharField(max_length=20, null=True)),
                ('Zip', models.IntegerField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20, null=True)),
                ('Mname', models.CharField(max_length=20, null=True)),
                ('Lname', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_type', models.CharField(max_length=30, null=True)),
                ('Date', models.DateField(null=True)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_type', models.CharField(max_length=30, null=True)),
                ('Area_code', models.IntegerField(max_length=3, null=True)),
                ('Number', models.IntegerField(max_length=8, null=True)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='Contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts'),
        ),
    ]
