# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181007_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
