# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Zip',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
