# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181007_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Area_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
