# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181007_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_type', models.CharField(max_length=30, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='Contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Phone_type',
            field=models.CharField(choices=[('Phone Type', 'Phone Type'), ('Home', 'Home'), ('Work', 'Work'), ('Cell', 'Cell'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
